version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket demo-sam-api --output-template-file packageTemplate.yaml
artifacts:
  type: zip
  files: 
    - template.yaml
    - packageTemplate.yaml